apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: app-grupo-3
  name: app-grupo-3
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: app-grupo-3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.service: app-grupo-3
    spec:
      containers:
        - image: jose10000/dev-grupo3:v1.12
          name: dev-grupo3
          ports:
            - containerPort: 3000
          resources: {}
      hostname: store
      restartPolicy: Always
status: {}
